# Generated by Django 4.2.7 on 2024-03-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('idcategory', models.BigAutoField(db_column='idCategory', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('idcus', models.BigAutoField(db_column='idCus', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('firstname', models.CharField(blank=True, db_column='firstName', null=True)),
                ('lastname', models.CharField(blank=True, db_column='lastName', null=True)),
                ('phone', models.CharField(blank=True, null=True)),
                ('email', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oder',
            fields=[
                ('idoder', models.BigAutoField(db_column='idOder', primary_key=True, serialize=False)),
                ('oderdate', models.DateTimeField(db_column='oderDate')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('paydate', models.DateTimeField(blank=True, db_column='payDate', null=True)),
            ],
            options={
                'db_table': 'oder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oderdetails',
            fields=[
                ('iddetail', models.BigAutoField(db_column='idDetail', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('quantity', models.BigIntegerField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oderDetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('idpay', models.BigAutoField(db_column='idPay', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('paytype', models.IntegerField(blank=True, db_column='payType', null=True)),
            ],
            options={
                'db_table': 'payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('idpro', models.BigAutoField(db_column='idPro', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('name', models.TextField(blank=True, null=True)),
                ('unitprice', models.FloatField(blank=True, db_column='unitPrice', null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('imgpro', models.TextField(blank=True, db_column='imgPro', null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
    ]
